### ISSUE TITLE
Errors after registering service worker

### ISSUE THREAD

**Issue by shoobzy** [tweedegolf/parcel-plugin-precaching-sw#1]
Hi there,

Experiencing some console errors in my dev environment after registering the service worker:

```
The script has an unsupported MIME type ('text/html').
Failed to load resource: net::ERR_INSECURE_RESPONSE
```

The service worker does not register in prod.

Package json configuration:

```
  "precachingSW": {
    "bypass": false,
    "allowed": [
      "js",
      "css",
      "map"
    ],
    "additional": [],
    "offlineUrl": "/",
    "fileName": "sw.js",
    "outDir": "./",
    "index.html": {
      "bypass": true
    }
  },

```

Thanks in advance,

Steve

**Comment by marlonbaeten** [comment]
Hi Steve,

Are you serving your development site over a [secure connection](https://parceljs.org/cli.html#enable-https)? Doing so might solve your problem.

**Comment by shoobzy** [comment]
Hi,

Yes, it's being served over https.

**Comment by shoobzy** [comment]
Sorry, I misread your earlier comment.

No, I hadn't assigned the `--https` to the watch.

I've now done this but am now struggling to assign a certificate in Chrome.

**Comment by marlonbaeten** [comment]
Maybe [mkcert](https://github.com/FiloSottile/mkcert) might help you. You can use the generated certificate for both you back-end server and for [parcel](https://parceljs.org/cli.html#set-a-custom-certificate).

**Comment by shoobzy** [comment]
Cool, I'll check it out.

Thanks for your help.
